version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
    # zookeeper意外退出时自动重启
    restart: always
    container_name: zookeeper
  kafka:
    build: .
    ports:
      - "${INSIDE_PORT}:${INSIDE_PORT}"
      - "${OUTSIDE_PORT}:${OUTSIDE_PORT}"
    restart: always
    environment:
      - TZ=CST-8
      - KAFKA_BROKER_ID=2
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_LOG_DIRS=/kafka/logs
      - KAFKA_ADVERTISED_LISTENERS=INSIDE://${INSIDE_HOSTNAME}:${INSIDE_PORT},OUTSIDE://${OUTSIDE_HOSTNAME}:${OUTSIDE_PORT}
      - KAFKA_LISTENERS=INSIDE://:${INSIDE_PORT},OUTSIDE://:${OUTSIDE_PORT}
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      - KAFKA_INTER_BROKER_LISTENER_NAME=INSIDE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${KAFKA_LOGS}:/kafka/logs
    labels:
      - project.source=
      - project.extra=public-image
      - project.depends=zookeeper
      - project.owner=LHZ
    container_name: kafka
